name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('shiny', 'rsconnect', 'scales', 'ggplot2', 'dplyr'), repos = 'https://cloud.r-project.org')"

    - name: Deploy app
      env:
        SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        Rscript -e "rsconnect::setAccountInfo(name=Sys.getenv('SHINYAPPS_NAME'), token=Sys.getenv('SHINYAPPS_TOKEN'), secret=Sys.getenv('SHINYAPPS_SECRET'))"
        Rscript -e "options(rsconnect.verbose = TRUE); rsconnect::deployApp(appDir = '.', forceUpdate = TRUE)"
