name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.2'  # or another version known to be supported by shinyapps.io

    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2

    - name: Deploy app
      env:
        SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        Rscript -e "rsconnect::setAccountInfo(name=Sys.getenv('SHINYAPPS_NAME'), token=Sys.getenv('SHINYAPPS_TOKEN'), secret=Sys.getenv('SHINYAPPS_SECRET'))"
        Rscript -e "options(rsconnect.verbose = TRUE); rsconnect::deployApp(appDir = '.', forceUpdate = TRUE)"
